### ISSUE TITLE
HashMap?

### ISSUE THREAD

**Issue by ArtemGr** [mohtar/rust-fastcgi#1]
Congratulations with publishing a cool library!

Please consider using BTreeMap instead of HashMap.
https://www.reddit.com/r/rust/comments/38s1n3/why_is_rust_much_slower_and_memory_consuming_than/crxf2jm

E.g. in the Request.

**Comment by mohtar** [comment]
You can always use something like `req.params().collect()` if you want to utilize another data structure.
