### ISSUE TITLE
FastCGI client?

### ISSUE THREAD

**Issue by ArtemGr** [mohtar/rust-fastcgi#2]
From browsing the code it seems to be a FastCGI server.
Would there be a FastCGI client as well?
Is it hard to implement?

**Comment by mohtar** [comment]
This library helps you build FastCGI web apps, similar to what is provided by the C FastCGI library `fcgiapp.h`. Pair this with any webserver that supports FastCGI e.g. lighttpd and you're good to go. I don't think there is a strong use case for "FastCGI client", and even if there is, then it falls outside the scope of this project.

**Comment by vi** [comment]
Shall it be documented explicitly that the library supports only one side of FastCGI (only server)?
