### ISSUE TITLE
Unable to get the response

### ISSUE THREAD

**Issue by sebui** [mohtar/rust-fastcgi#4]
I'm trying to run the exemple with unix tcp listener, the request perform well but the response doesn't work.

**Comment by mohtar** [comment]
Do you have a minimal test case for this?

**Comment by sebui** [comment]
Yes.
I'm on Arch 64, rustc 1.4.0
https://gist.github.com/sebui/70cfab4c6e6900446bd7
Minimalist, I've quickly created it from my workplace. Nginx conf works fine with my C++ code project.

I don't know how I can debug this kind of problem. How did you do during the development ?

**Comment by mohtar** [comment]
Tried your example. Works fine on my setup.

For debugging, you can try monitoring the communications between the FastCGI app and the HTTP server. Use this patch: https://gist.github.com/mohtar/c9372616d1d9698857c4

**Comment by mohtar** [comment]
Okay, it seems that this bug is specific to Linux build of Nginx. I will investigate further.

**Comment by mohtar** [comment]
Should be fixed by now. Thank you for contributing!
