### ISSUE TITLE
Documentation link redirects to crates.io

### ISSUE THREAD

**Issue by Knifa** [mohtar/rust-fastcgi#6]
http://www.rust-ci.org/mohtar/rust-fastcgi/doc/fastcgi/ seems to redirect to http://crates.io/ --- bit confusing!

**Comment by mohtar** [comment]
Seems like rust-ci.org has been shut down. You can generate the docs yourself in the mean time.

**Comment by retep998** [comment]
Now the link redirects to some junk advertisement website. Maybe it would be a good idea to publish a new version that links to docs.rs instead?

**Comment by mohtar** [comment]
Thanks! I had no idea docs.rs existed

**Comment by retep998** [comment]
Don't forget the link in `Cargo.toml`, since that is what people on crates.io are clicking on.
