### ISSUE TITLE
How to run the example?

### ISSUE THREAD

**Issue by wezm** [mohtar/rust-fastcgi#8]
How is the example expected to be run? If I run it manually I get:

```
thread 'main' panicked at 'Socket operation on non-socket (os error 88)', /home/wmoore/.cargo/registry/src/github.com-1ecc6299db9ec823/fastcgi-1.0.0-beta/src/lib.rs:573
```

Since `fastcgi::run` is documented as UNIX only I'm assuming it's trying to use a UNIX domain socket or similar. Where/how do I pass the path to the socket?

Sample lighttpd config for the example would be super helpful also if you have it.

**Comment by mohtar** [comment]
The socket is expected at file descriptor 0. It's the responsibility of the web server to create the socket file then pass it to the FastCGI executable.

Here's a sample snippet for the lighttpd config:

    fastcgi.server += ( "/" =>
        ((
            "socket" => "/tmp/test-fcgi.sock",
            "bin-path" => "/path/to/fastcgi-executable",
            "check-local" => "disable",
            "max-procs" => 8,
        ))
    )

Make sure mod_fastcgi is enabled.

**Comment by wezm** [comment]
Awesome! I got it working now, thanks.

**Comment by cpenning** [comment]
Also you can use [`spawn-fcgi`](https://redmine.lighttpd.net/projects/spawn-fcgi/wiki) for testing with other web servers—including home-grown (part of the `lighthttpd` suite, but works with anything.)
