### ISSUE TITLE
Documentation site became phishing site

### ISSUE THREAD

**Issue by yookoala** [mohtar/rust-fastcgi#9]
The documentation link on [crate.io](https://crates.io/crates/fastcgi) is currently this:
* http://www.rust-ci.org/mohtar/rust-fastcgi/doc/fastcgi/

Apparently the domain rust-ci.org has been expired and was purchased by phisher. (I went to the page and it told me that I won some gift to Disney from Google.)

It would be best to update the documentation link.

**Comment by mohtar** [comment]
Fixed. Thanks!
